closes quicksurf/quicksurf-bash-utilities#1
This changeset checks to see if a git script is currently in a git
before performing the git commands it is supposed to perform.

If not currently in a git repo, then the script is exited with a status
code of 1.

	modified:   add
	modified:   commit
	new file:   ig
	modified:   log
	modified:   master
	modified:   pb
	modified:   pull
	modified:   push
	modified:   status
	modified:   wip

diff --git a/status b/status
--- a/status
+++ b/status
@@ -28,6 +28,11 @@
 #
 #Feel free to modify to meet your needs.
 
-
+#Check to see if we are in a git repo, and if so, proceed, otherwise, exit with
+#a failure.
+if [ $(ig) -ne 0 ]
+    then
+        exit 1
+fi
 
 git status
